name: GitHub Pages deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REACT_APP_SERVER_URI: https://pg-backend-nestjs.onrender.com/
      REACT_APP_WS_SERVER_URI: wss://pg-backend-nestjs.onrender.com/

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List build directory contents
        run: ls -la ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./dist

      - name: Clean up
        run: |
          pkill -f node
          pkill -f npm
